---
  version: 1.0

  arch: mingw64

  msys2-version: ">3.6.5"

  description: "Install the 'git-bash.exe' in an MSYS2 environment (MINGW64). Does not work on Windows prior to version 8.1!"

  steps:

    - name: '#1'
      description: "Add resource locations for 'git-for-windows-x86_64' and install PGP keys. Upgrade system (synchronize with new repositories)."
      files:
        - '/etc/pacman.conf':
            before_line: "[mingw32]"
            new_lines:
              - "[git-for-windows-x86_64]"
              - "Server = https://raw.githubusercontent.com/git-for-windows/pacman-repo/refs/heads/x86_64"
              - ""
              - "[git-for-windows-mingw32]"
              - "Server = https://raw.githubusercontent.com/git-for-windows/pacman-repo/refs/heads/i686"
              - ""
      packages:
        - "git"
      commands:
        - "curl -L https://raw.githubusercontent.com/git-for-windows/build-extra/HEAD/git-for-windows-keyring/git-for-windows.gpg | sh -c 'pacman-key --add -'"
        - "sh -c 'pacman-key --lsign-key E8325679DFFF09668AD8D7B67115A57376871B1C'"
        - "sh -c 'pacman-key --lsign-key 3B6D86A1BA7701CD0F23AED888138B9E1A9F3986'"
        - "sh -c 'pacman -Syyuu --noconfirm'"

    - name: '#2'
      description: "Update MSYS2 packages database (sync)."
      commands:
        - "sh -c 'pacman -Suu --noconfirm'"

    - name: '#3'
      description: "Install new (git-bash) packages."
      files:
        - '/etc/inputrc':
            move: "/etc/inputrc.bak"
      packages:
        - "mingw-w64-x86_64-git"
        - "mingw-w64-x86_64-git-doc-html"
        - "mingw-w64-x86_64-git-doc-man"
        - "mingw-w64-x86_64-git-extra"
        - "mingw-w64-x86_64-git-credential-manager"
      commands:
        - "sh -c 'echo \"DONE. You'll find the git-bash.exe in the root folder of the MSYS2 installation.\"'"

    - name: '#4'
      description: "Start ssh-agent for user automatically when MSYS2 bash starts."
      files:
        - 'ssh-agent.sh':
            target_dir: '/etc/profile.d'
      packages: 
        - "gnupg"
