---
  version: 1.0

  arch: clang64

  msys2-version: ">3.6.5"
  
  goals: "Establish an LLVM toolchain with Rust compiler frontend to build Windows [10] native applications."

  steps:

    - name: "#1"
      description: "Update MSYS2  packages."
      commands: 
        - "sh -c 'pacman -Syu --noconfirm'"
        
    - name: "#2"
      description: "Install tools needed for downloading, compiling and generating."
      packages:
        - "autotools"
        - "base-devel"
        - "cmake"
        - "cygutils"
        - "diffutils"
        - "cmake"
        - "gcc"
        - "git"
        - "help2man"
        - "patch"
        - "perl-File-next"
        - "rsync"
        - "python"
        - "unzip"
        - "zip"
        - "zlib-devel"
        
    - name: '#3'
      description: "Update MSYS2 packages database (sync)"
      commands:
        - "sh -c 'pacman -Syyuu --noconfirm'"
        
    - name: '#4'
      description: "Install components in 'mingw-w64-clang-x86_64-toolchain'"
      packages: 
        - "mingw-w64-clang-x86_64-cc"
        - "mingw-w64-clang-x86_64-crt"
        - "mingw-w64-clang-x86_64-clang-21"
        - "mingw-w64-clang-x86_64-compiler-rt-21"
        - "mingw-w64-clang-x86_64-lld-21"
        - "mingw-w64-clang-x86_64-llvm-21"
        - "mingw-w64-clang-x86_64-clang"
        - "mingw-w64-clang-x86_64-clang-analyzer"
        - "mingw-w64-clang-x86_64-clang-libs"
        - "mingw-w64-clang-x86_64-clang-tools-extra"
        - "mingw-w64-clang-x86_64-cmake"
        - "mingw-w64-clang-x86_64-compiler-rt"
        - "mingw-w64-clang-x86_64-headers"
        - "mingw-w64-clang-x86_64-http-parser"
        - "mingw-w64-clang-x86_64-libc++"
        - "mingw-w64-clang-x86_64-libgit2"
        - "mingw-w64-clang-x86_64-libunwind"
        - "mingw-w64-clang-x86_64-libmangle"
        - "mingw-w64-clang-x86_64-libssh2"
        - "mingw-w64-clang-x86_64-libwinpthread"
        - "mingw-w64-clang-x86_64-lld"
        - "mingw-w64-clang-x86_64-lldb"
        - "mingw-w64-clang-x86_64-llvm"
        - "mingw-w64-clang-x86_64-llvm-libs"
        - "mingw-w64-clang-x86_64-llvm-openmp"
        - "mingw-w64-clang-x86_64-llvm-tools"
        - "mingw-w64-clang-x86_64-nasm"
        - "mingw-w64-clang-x86_64-make"
        - "mingw-w64-clang-x86_64-pkgconf"
        - "mingw-w64-clang-x86_64-tools"
        - "mingw-w64-clang-x86_64-winpthreads"
        - "mingw-w64-clang-x86_64-winstorecompat"
        
    - name: '#5'
      description: "Update MSYS2 packages database (sync)"
      commands:
        - "sh -c 'pacman -Suy --noconfirm'"
        
    - name: "#6"
      description: "Install Rust tools (rustup et al.) and dependencies"
      packages:
        - "rust"
        - "mingw-w64-clang-x86_64-rust"
        - "mingw-w64-clang-x86_64-rust-bindgen"
        - "mingw-w64-clang-x86_64-rust-emscripten"
        - "mingw-w64-clang-x86_64-rust-src"
        - "mingw-w64-clang-x86_64-rust-wasm"
        - "mingw-w64-clang-x86_64-rustup"
        
    - name: '#7'
      description: "Install Clang64 libraries for GTK4 development on Windows"
      packages:
        - "gettext-devel"
        - "glib2"
        - "glib2-devel"
        - "iconv"
        - "libffi-devel"
        - "libiconv-devel"
        - "mingw-w64-clang-x86_64-cairo"
        - "mingw-w64-clang-x86_64-pango"
        - "mingw-w64-clang-x86_64-gdk-pixbuf2"
        - "mingw-w64-clang-x86_64-graphene"
        - "mingw-w64-clang-x86_64-gtk4"
