---
  version: 1.0

  platform: ucrt64

  msys2-version: ">3.6.5"

  steps:
    - name: "#1"
      description: "Add required build-time dependencies for the LLVM compiler."
      packages:
        - "base-devel"


    
    - name: "#4"
      description: "Compile the LLVM package."
      commands:
        - "echo TODO!!"