---
  version: 1.0

  arch: clangarm64

  msys2-version: ">3.6.7-4"

  steps:
    - name: "#1"
      description: "Update MSYS2 packages"
      commands: 
        - "sh -c 'pacman -Syu --noconfirm'"
    
    - name: "#2"
      description: "Add Qt5 libraries."
      packages:
        - "mingw-w64-clang-aarch64-qt5"
        - "mingw-w64-clang-aarch64-qt5-debug"
        - "mingw-w64-clang-aarch64-qtwebkit"

    - name: "#3"
      description: "Install CLANG64 toolchain (LLVM) and dev tools (Python)"
      packages:
        - "mingw-w64-clang-aarch64-toolchain"
        - "mingw-w64-clang-aarch64-cc"
        - "mingw-w64-clang-aarch64-cmake-gui"
        - "mingw-w64-clang-aarch64-meson"
        - "mingw-w64-clang-aarch64-ninja"
        - "mingw-w64-clang-aarch64-git-gui"
        - "mingw-w64-clang-aarch64-git-for-windows-addons"
        - "mingw-w64-clang-aarch64-python-pyqt5"
        - "mingw-w64-clang-aarch64-python-pyqt5-3d"
        - "mingw-w64-clang-aarch64-python-build"
        - "mingw-w64-clang-aarch64-python-installer"
        - "mingw-w64-clang-aarch64-python-setuptools"
        - "mingw-w64-clang-aarch64-qt-creator"
        - "python"
        - "python-pip"
        - "cmake"
        - "meson"
        
    - name: "#4"
      description: "TODO"
      commands:
        - "sh -c 'echo DONE!'"
        
