---
  version: 1.0

  platform: ucrt64

  msys2-version: ">3.6.5"

  steps:
    - name: "#1"
      description: "Add required dependencies for GTK3."
      packages:
        - "mingw-w64-ucrt-x86_64-adwaita-icon-theme"
        - "mingw-w64-ucrt-x86_64-cairo"
        - "mingw-w64-ucrt-x86_64-cc-libs"
        - "mingw-w64-ucrt-x86_64-gdk-pixbuf2"
        - "mingw-w64-ucrt-x86_64-glib2"
        - "mingw-w64-ucrt-x86_64-graphene"
        - "mingw-w64-ucrt-x86_64-gst-plugins-bad-libs"
        - "mingw-w64-ucrt-x86_64-gtk-update-icon-cache"
        - "mingw-w64-ucrt-x86_64-json-glib"
        - "mingw-w64-ucrt-x86_64-libepoxy"
        - "mingw-w64-ucrt-x86_64-pango"
        - "mingw-w64-ucrt-x86_64-shared-mime-info"
        - "mingw-w64-ucrt-x86_64-vulkan-loader"
    
    - name: "#2"
      description: "Install additional plugins (mingw-w64-ucrt-x86_64-gst-plugins-good)"
      packages:
        - "mingw-w64-ucrt-x86_64-bzip2"
        - "mingw-w64-ucrt-x86_64-cairo"
        - "mingw-w64-ucrt-x86_64-flac"
        - "mingw-w64-ucrt-x86_64-gdk-pixbuf2"
        - "mingw-w64-ucrt-x86_64-gettext-runtime"
        - "mingw-w64-ucrt-x86_64-glib2"
        - "mingw-w64-ucrt-x86_64-gst-plugins-base"
        - "mingw-w64-ucrt-x86_64-gstreamer"
        - "mingw-w64-ucrt-x86_64-lame"
        - "mingw-w64-ucrt-x86_64-libcaca"
        - "mingw-w64-ucrt-x86_64-libjpeg"
        - "mingw-w64-ucrt-x86_64-libpng"
        - "mingw-w64-ucrt-x86_64-libshout"
        - "mingw-w64-ucrt-x86_64-libsoup3"
        - "mingw-w64-ucrt-x86_64-libvpx"
        - "mingw-w64-ucrt-x86_64-libxml2"
        - "mingw-w64-ucrt-x86_64-mpg123"
        - "mingw-w64-ucrt-x86_64-opencore-amr"
        - "mingw-w64-ucrt-x86_64-speex"
        - "mingw-w64-ucrt-x86_64-taglib"
        - "mingw-w64-ucrt-x86_64-twolame"
        - "mingw-w64-ucrt-x86_64-wavpack"
        - "mingw-w64-ucrt-x86_64-zlib"

    - name: "#3"
      description: "Install mingw-w64-ucrt-x86_64-toolchain."
      packages: 
        - "mingw-w64-ucrt-x86_64-binutils"
        - "mingw-w64-ucrt-x86_64-crt-git"
        - "mingw-w64-ucrt-x86_64-gcc"
        - "mingw-w64-ucrt-x86_64-gdb"
        - "mingw-w64-ucrt-x86_64-gdb-multiarch"
        - "mingw-w64-ucrt-x86_64-headers-git"
        - "mingw-w64-ucrt-x86_64-libmangle-git"
        - "mingw-w64-ucrt-x86_64-libwinpthread"
        - "mingw-w64-ucrt-x86_64-winpthreads"
        - "mingw-w64-ucrt-x86_64-make"
        - "mingw-w64-ucrt-x86_64-pkgconf"
        - "mingw-w64-ucrt-x86_64-tools-git"
        - "mingw-w64-ucrt-x86_64-winstorecompat-git"

      commands:
        - "echo TODO!!"

        