---
  version: 1.0

  arch: mingw64

  msys2-version: ">3.6.7-4"

  steps:

    - name: "#1"
      description: "Update MSYS2 packages."
      commands: 
        - "sh -c 'pacman -Syu --noconfirm'"
        
    - name: "#2"
      description: "Add Qt6 libraries."
      packages:
        - "mingw-w64-x86_64-qt6"

    - name: "#3"
      description: "Add Python, required Python extensions, as well as supporting tools, e.g. qtcreator."
      packages:
        - "python"
        - "mingw-w64-x86_64-meson"
        - "mingw-w64-x86_64-python"
        - "mingw-w64-x86_64-python-pyqt6"
        - "mingw-w64-x86_64-cmake-gui"
        - "mingw-w64-x86_64-qt-creator"
        - "mingw-w64-x86_64-git-gui"
        - "mingw-w64-x86_64-git-for-windows-addons"
        
